name: TransformerGraphRAG
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.8.3=h4c7d964_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - liblzma=5.8.1=h2466b09_2
  - libmpdec=4.0.0=h2466b09_0
  - libsqlite=3.50.4=hf5d6505_0
  - libzlib=1.3.1=h2466b09_2
  - openssl=3.5.2=h725018a_0
  - pip=25.2=pyh145f28c_0
  - python=3.13.7=hdf00ec1_100_cp313
  - python_abi=3.13=8_cp313
  - tk=8.6.13=h2c6b04d_2
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h41ae7f8_31
  - vc14_runtime=14.44.35208=h818238b_31
  - vcomp14=14.44.35208=h818238b_31
  - pip:
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.10.0
      - asgiref==3.9.1
      - attrs==25.3.0
      - backoff==2.2.1
      - bcrypt==4.3.0
      - blinker==1.9.0
      - build==1.3.0
      - cachetools==5.5.2
      - certifi==2025.8.3
      - chardet==5.2.0
      - charset-normalizer==3.4.3
      - chromadb==1.0.21
      - click==8.2.1
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - django==5.2.6
      - djangorestframework==3.16.1
      - durationpy==0.10
      - filelock==3.19.1
      - flask==3.1.2
      - flask-cors==6.0.1
      - flatbuffers==25.2.10
      - fonttools==4.60.0
      - frozenlist==1.7.0
      - fsspec==2025.9.0
      - google-auth==2.40.3
      - googleapis-common-protos==1.70.0
      - greenlet==3.2.4
      - grpcio==1.75.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - httpx-sse==0.4.1
      - huggingface-hub==0.35.0
      - humanfriendly==10.0
      - idna==3.10
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.11.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - kubernetes==33.1.0
      - langchain==0.3.27
      - langchain-chroma==0.2.6
      - langchain-community==0.3.29
      - langchain-core==0.3.76
      - langchain-ollama==0.3.8
      - langchain-text-splitters==0.3.11
      - langsmith==0.4.28
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.10.6
      - mdurl==0.1.2
      - mmh3==5.2.0
      - mpmath==1.3.0
      - multidict==6.6.4
      - mypy-extensions==1.1.0
      - numpy==2.3.3
      - oauthlib==3.3.1
      - ollama==0.5.4
      - onnxruntime==1.22.1
      - openai==1.108.1
      - opentelemetry-api==1.37.0
      - opentelemetry-exporter-otlp-proto-common==1.37.0
      - opentelemetry-exporter-otlp-proto-grpc==1.37.0
      - opentelemetry-proto==1.37.0
      - opentelemetry-sdk==1.37.0
      - opentelemetry-semantic-conventions==0.58b0
      - orjson==3.11.3
      - overrides==7.7.0
      - packaging==25.0
      - pillow==11.3.0
      - posthog==5.4.0
      - propcache==0.3.2
      - protobuf==6.32.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.2
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydantic-settings==2.10.1
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pyreadline3==3.5.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==14.1.0
      - rpds-py==0.27.1
      - rsa==4.9.1
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.43
      - sqlparse==0.5.3
      - sse-starlette==3.0.2
      - starlette==0.48.0
      - sympy==1.14.0
      - tenacity==9.1.2
      - tokenizers==0.22.0
      - tqdm==4.67.1
      - typer==0.17.4
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.35.0
      - watchfiles==1.1.0
      - websocket-client==1.8.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - yarl==1.20.1
      - zipp==3.23.0
      - zstandard==0.25.0
prefix: D:\miniconda\envs\TransformerGraphRAG
